### ISSUE TITLE
Unable to log into Google with automated Chrome

### ISSUE THREAD

**Issue by bpollack** [perkeep/gphotos-cdp#10]
I'd swear this had worked before, but now, when I attempt to run this, the automated Chrome window refuses to allow me to log in. The details say that automated tooling cannot be used with Chrome to log into my account. Is there some way around this that I'm missing?

**Comment by bpollack** [comment]
Never mind, I see this is a duplicate of #1 . Would you accept a patch noting this in the README? Seems like it's hitting a few of us, for whatever reason.

**Comment by hayschan** [comment]
Same issue for me.  I'm on macOS with 81.0 Chrome
