### ISSUE TITLE
Timeout waiting for left navigation

### ISSUE THREAD

**Issue by mwgnr** [perkeep/gphotos-cdp#12]
I'm getting the following error message after downloading the last item: "timeout waiting for left navigation". As a workaround, I get the url of the first item and compare it with the "location" variable. If they are the same "navN" breaks. Is this expected behavior?

**Comment by mpl** [comment]
Are you saying you're seeing an error for the very last item to be downloaded (i.e. the most recent one) in your collection?
If yes, no that is not expected, but otoh tbh I didn't do a full rerun on all my collection after the latest changes, so it's not that surprising either.
I'll retest and confirm, thanks.

**Comment by mwgnr** [comment]
Yes, I get this error after downloading the most recent photo: 

```
2020/04/06 16:04:44 Marking https://photos.google.com/u/0/photo/A...k_ as done
2020/04/06 16:05:44 error at https://photos.google.com/u/0/photo/A...k_: timeout waiting for left navigation
```

**Comment by JakeWharton** [comment]
Same for both my incremental sync's. They're hanging on the most recent photo.

**Comment by mpl** [comment]
ok, I can reproduce, thanks.

**Comment by mpl** [comment]
Alright, https://github.com/perkeep/gphotos-cdp/pull/14 should take care of the problem, even though it's not very fancy.

Can you please try it out and let me know if it works for you?

**Comment by leuasseurfarrelds247-arch** [comment]
6996da126cd50ccd812cfee1146b481fa3ec34fe[]()

**Comment by leuasseurfarrelds247-arch** [comment]
[]()
