### ISSUE TITLE
Does the tool sync photo modifications?

### ISSUE THREAD

**Issue by benblo** [perkeep/gphotos-cdp#13]
Hi! Not sure what to expect from the tool, once I've made the initial backup, if I then modify photos (from the web interface or mobile app etc), will it sync them on subsequent runs? Or does it _only_ download originals?
Basically I'm wondering if the tool has access to the elusive "last modified time". I was initially tempted to use rclone as a backup solution, but was put off by the [limitations](https://rclone.org/googlephotos/#limitations).

Could cpd potentially be used as a 2-ways sync tool? My internet access is not super fast, and viewing pictures in a browser isn't ideal... I still miss Picasa, and having pictures right there in the local filesystem :'( !

**Comment by mpl** [comment]
On Sun, 3 May 2020 at 06:17, Benoit FOULETIER <notifications@github.com>
wrote:

> Hi! Not sure what to expect from the tool, once I've made the initial
> backup, if I then modify photos (from the web interface or mobile app etc),
> will it sync them on subsequent runs? Or does it *only* download
> originals?
> Basically I'm wondering if the tool has access to the elusive "last
> modified time". I was initially tempted to use rclone as a backup solution,
> but was put off by the limitations
> <https://rclone.org/googlephotos/#limitations>.
>
Yes, I think it would. But you may have to use the -start file to force to
rerun from a point anterior to your photo's creation date. And/Or to remove
the progress tracking marker at $HOME/Downloads/gphotos-cd/.lastdone

> Could cpd potentially be used as a 2-ways sync tool? My internet access is
> not super fast, and viewing pictures in a browser isn't ideal... I still
> miss Picasa, and having pictures right there in the local filesystem :'( !
>
If by 2-ways, you mean to use it to upload files to Google Photos as well?
In theory I think it would be possible, but it does not do that at all at
the moment.

**Comment by benblo** [comment]
Thanks! Yes my question was more about the theoretical capabilities; if this cdp-wrapper can act as a workaround to a proper/complete API, then I'd be happy to write my own tool to do what I need. I guess I'll just have to find some time to poke at it and see what falls.

If I understand correctly, one thing that's missing anyway is a way to ask for a list of all new events/modifications since <some date>, right?

How stable do you imagine this DevTools Protocol thing to be? I saw the "what if" header in the readme, I'm just asking for a gut feeling as this is far from my area of expertise, is it more "so brittle it'll change every month" or "good chance it'll last for years"?

**Comment by mpl** [comment]
If you're asking about the viability of https://github.com/chromedp/chromedp , given that @mvdan is maintaining it at the moment, I'm pretty confident about it.

**Comment by mpl** [comment]
As the question seems to be answered, I'll just go ahead and close this issue.
