### ISSUE TITLE
Out of curiousity, why do you nav to end with PgDowns rather than Ctrl+End ?

### ISSUE THREAD

**Issue by aviramsegal** [perkeep/gphotos-cdp#28]
https://github.com/perkeep/gphotos-cdp/blob/e9d1979707191993f1c879ae93f8dd810697fd6e/main.go#L315

It feels like Ctrl+End is much more efficient as it just jumps to the end at once rather goes through your entire library.
Is there any specific reason for using PgDowns and comparing screenthots ?

**Comment by mpl** [comment]
No reason other than ignorance. If Ctrl+end works better and works on all
platforms, then we should definitely use it.

**Comment by aviramsegal** [comment]
Thanks for the quick reply.
On Mac and Windows Ctrl+End works.
I'll find some time this week to test on Linux and send a PR if it works s well.

**Comment by aviramsegal** [comment]
Took another look at it
Ctrl+End does immediately get to the end but every once in a while it jumps back a bit.
it isn't much faster than current behavior on a very big library.
