### ISSUE TITLE
Consider setting file creation/update date from EXIF information

### ISSUE THREAD

**Issue by JakeWharton** [perkeep/gphotos-cdp#7]
This could be done as a post-processing step externally, but then you either have to do it on all files every time or try to track new items. It doesn't seem outside of the responsibility of the tool to consider making this a built-in feature.

**Comment by mpl** [comment]
@JakeWharton I feel like this falls exactly under the use-case of the -run flag, no?

**Comment by JakeWharton** [comment]
Yep! Not sure how I overlooked that. Thanks!
